### ISSUE TITLE
serv00无法访问https://cloudflared.bowring.uk/binaries/cloudflared-freebsd-latest.7z

### ISSUE THREAD

**Issue by bet-io** [giturass/cloudflared_freebsd#1]
s9 不能访问https://cloudflared.bowring.uk/binaries/cloudflared-freebsd-latest.7z 估计是域名被拉进了黑名单
![Otfjwa.png](https://ooo.0x0.ooo/2024/08/30/Otfjwa.png)

**Comment by bet-io** [comment]
算了 还是

**Comment by giturass** [comment]
download 到本地然后上传？
